### ISSUE TITLE
Use library helper, not regex

### ISSUE THREAD

**Issue by langsamu** [ukparliament/grom#103]
[Grom::Reader#read_data@31](https://github.com/ukparliament/grom/blob/development/lib/grom/reader.rb#L31) checks whether a statement object is a URI node. It currently uses regex.

I think it should use RDF.rb utility methods instead.

[RDF::Statement#object](http://www.rubydoc.info/github/ruby-rdf/rdf/RDF/Statement#object-instance_method) is an [RDF::Term](http://www.rubydoc.info/github/ruby-rdf/rdf/RDF/Term), which is an [RDF::Value](http://www.rubydoc.info/github/ruby-rdf/rdf/RDF/Value), which has a [#uri?](http://www.rubydoc.info/github/ruby-rdf/rdf/RDF/Value#uri%3F-instance_method) method.

**Comment by katylouise** [comment]
#113 - Fixed issue.
