### ISSUE TITLE
License link is a 404

### ISSUE THREAD

**Issue by njh** [ukparliament/grom#131]
Was interested in what the Open Parliament Licence looked like but it is a 404:
http://www.parliament.uk/site-information/copyright/open-parliament-licence/

What was the reason for not using a standard license?

**Comment by mattrayner** [comment]
Hi Nicholas,
 Looks like someone moved the page - it's available here:
https://www.parliament.uk/site-information/copyright-parliament/open-parliament-licence/

It's largely MIT with a couple of changes that covers the use of parliamentary iconography and data :+1:

I'll update the link and stimulate an internal conversation about licenses. In some places we have used standard MIT, I'll see why we didn't here :)

**Comment by mattrayner** [comment]
@oddtype any opinion here?

**Comment by oddtype** [comment]
@mattrayner it was you who [changed the license from MIT to OPL](https://github.com/ukparliament/grom/commit/3743e2faa58af9a365f47b533514780184ffa28e#diff-04c6e90faac2675aa89e2176d2eec7d8) - part of a mass README update so perhaps a mistake? Prior to you joining Parliament, almost a year ago, @jakemulley and I had discussed how MIT was the most appropriate default for licensing of software (not content). I confirmed that decision and communicated it up the chain although it hasn't been enshrined into any team policy. You should feel free to revert it to MIT.

**Comment by mattrayner** [comment]
@oddtype 😂 so it was... I've added a PR to change it back

**Comment by njh** [comment]
Fantastic outcome, thank you!
